<?php
//FUNCION QUE RECIBIRÁ EL NOMBRE DEL HUERTO QUE SERA PREDETERMINADO EL PRIMERO Y LUEGO SE EJECUTA LA FUNCION
//CADA VEZ QUE EL SELECT CAMBIA, DEVOLVERA UN OBJETO CON TODAS LAS MEDIDAS ACTUALES, CADA INTERVALO DE TIEMPO
//SE EJECUTA LA FUNCION DE NUEVO PARA RECOGER LOS DATOS