<?php
//FUNCION A LA QUE SE LE PASARAN DOS FECHAS, PARA EN SQL HACER UN SELECT BETWEEN DE FECHAS
//LUEGO DEVUELVE TODAS LAS MEDIDAS DE ESAS FECHAS Y YA EL JS LO GESTIONA
//LUEGO EL CODIGO DE CHART TAMBIEN PODRIA GESTIONAR LO DE LAS MEDIAS MENSUALES Y TAL